### PR TITLE
Add Last commit status and repo size

### PR DESCRIPTION
**Pull request by vj-abishek**
Added Badges based on #6  this issue

### CODE REVIEW

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
I don't think we should put every badge in a new line.

**Comment by vj-abishek** [comment]
@YashKumarVerma fixed 👍

**Review by YashKumarVerma — APPROVED** [review]
LGTM

**Comment by lopeselio** [comment]
@vj-abishek  need to reolsve conflicts

**Comment by vj-abishek** [comment]
@lopeselio working on it

**Comment by vj-abishek** [comment]
@lopeselio fixed

**Pull request merged**
