### PR TITLE
added a database connection script

### PR DESCRIPTION
**Pull request by veeralsharma**
added a script that connects you to mongodb database

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
We're using mysql database, could you update the pr please?

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
Please adapt as per mysql

**Comment by veeralsharma** [comment]
made changes you can review

**Review by YashKumarVerma — APPROVED** [review]
LGTM

**Comment by YashKumarVerma** [comment]
Please fix the merge conflicts so that we can merge this.

**Comment by veeralsharma** [comment]
resolved conflicts

**Review by YashKumarVerma — APPROVED** [review]
LGTM

**Comment by veeralsharma** [comment]
you can merge then

**Comment by YashKumarVerma** [comment]
We would be doing it shortly.

**Comment by YashKumarVerma** [comment]
Fixes https://github.com/ACM-VIT/dolos/issues/10

**Comment by veeralsharma** [comment]
hey can you add hacktoberfest-accepted label to it

**Pull request merged**
