### PR TITLE
Added Hacktoberfest Shields.io badge

### PR DESCRIPTION
**Pull request by iamrajatg**
Added Hacktoberfest Shields.io badge
This bagde shows open Issues labelled with Hacktoberfest,PRs created in October and No. of days left in october . 

Capture

### CODE REVIEW

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
Can you change the style to match the other badges? 

hint: it's for-the !

**Comment by iamrajatg** [comment]
> Can you change the style to match the other badges?
> 
> hint: it's for-the !

Sure!

**Review by iamrajatg — COMMENTED** [review]
Badge style has been changed in next commit

**Review by YashKumarVerma — APPROVED** [review]
LGTM

**Comment by YashKumarVerma** [comment]
Thanks !

**Pull request merged**
